Big Sur support
microsoft/FigmaSharp pull request #297
Opened 2020-09-09 12:23 UTC by hbons

2020-10-12 09:09 UTC, vancura commented
@hbons We should merge this before the branches differ too much. Let's take a look at it this week.

2020-10-12 09:46 UTC, hbons commented on FigmaSharp.Controls/FigmaSharp.Controls.Cocoa/Converters/Misc/EmbeddedWindowConverter.cs
> +			if (MacSystemInformation.OsVersion < MacSystemInformation.BigSur)
I think this should be flipped? :)

2020-10-12 11:49 UTC, netonjm commented on FigmaSharp.Controls/FigmaSharp.Controls.Cocoa/Converters/Misc/EmbeddedWindowConverter.cs
> +			if (MacSystemInformation.OsVersion < MacSystemInformation.BigSur)
It was flipped in the next commit 😄

2020-10-13 11:01 UTC, netonjm requested changes
The PR needs address some changes. I added some small fixes to don't break build in systems < BigSur, now we have a new configuration DebugBigSur and ReleaseBigSur to enable this new API's

2021-06-02 12:04 UTC, netonjm commented
@hbons any update on this PR?

2021-06-02 12:23 UTC, hbons commented
nope... no time yet.

2023-04-04 17:50 UTC, closed without merging